github: [metadata]
title: arkku.dev
description: Arkku codes and tinkers with electronics, microcontrollers, and retro computers.
encoding: UTF-8
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  gfm_quirks: [paragraph_end, no_auto_typographic]
  toc_levels: 2..3
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
future: true
jailed: false
theme: jekyll-theme-primer
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
github_username: arkku
twitter_username: kkuloves
author:
  github: arkku
  facebook: arkku
  instagram: arkku
  twitter: kkuloves
  youtube: arkku
  flickr: arkku
feed:
  path: "/feed/atom.xml"
  categories:
    - retrocomputing
    - electronics
    - programming
    - computers
    - hardware
    - software
    - audio
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true
optional_front_matter:
  remove_originals: true
